init: depend on libselinux_defaults
In file included from device/oneplus/oneplus2/init/init_oneplus2.cpp:35:
system/core/init/util.h:29:10: fatal error: 'selinux/label.h' file not found

Change-Id: Id27b13647465e03a9131e385876e0cf655baccca